#!/bin/bash

mvn -q dependency:build-classpath -Dmdep.outputFile=classpath 

rm -f src/java/junit/framework/subpackage/*

mvn -q clean compile

echo "================================"
echo "Run 1. Compiled classes: "
find target/classes

java -cp target/classes:`cat classpath` datomic.JaninoRepro3

cp siderail/Breaker.java src/java/junit/framework/subpackage/

mvn -q clean compile

echo "================================"
echo "Run 2. Compiled classes: "
find target/classes

java -cp target/classes:`cat classpath` datomic.JaninoRepro3

